import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import TopBar from "@/components/topbar";
import NavigationBar from "@/components/navigation-bar";
import { Maven_Pro } from "next/font/google";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const maven = Maven_Pro({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${maven.className} antialiased`}>
        <div className="min-h-screen flex bg-white text-gray-600">
          <NavigationBar />

          <main className="flex-1 py-8 pl-2 pr-16">
            <TopBar />

            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
